server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /bowls {
        proxy_pass http://backend:8000;
    }

    location /bm-entries {
        proxy_pass http://backend:8000;
    }

    location /dashboard {
        proxy_pass http://backend:8000;
    }

    location /episode-entries {
        proxy_pass http://backend:8000;
    }

    location /food-entries {
        proxy_pass http://backend:8000;
    }

    location /fluid-entries {
        proxy_pass http://backend:8000;
    }

    location /foods {
        proxy_pass http://backend:8000;
    }

    location /health {
        proxy_pass http://backend:8000;
    }

    location /medication-entries {
        proxy_pass http://backend:8000;
    }

    location /vet-visit-entries {
        proxy_pass http://backend:8000;
    }

    location /weight-entries {
        proxy_pass http://backend:8000;
    }

    location /water-entries {
        proxy_pass http://backend:8000;
    }
}
